// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// knn_dist
double knn_dist(NumericVector y, int knn, int position);
RcppExport SEXP _miknn_knn_dist(SEXP ySEXP, SEXP knnSEXP, SEXP positionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type knn(knnSEXP);
    Rcpp::traits::input_parameter< int >::type position(positionSEXP);
    rcpp_result_gen = Rcpp::wrap(knn_dist(y, knn, position));
    return rcpp_result_gen;
END_RCPP
}
// kDistC
double kDistC(NumericVector y, int knn, int position);
RcppExport SEXP _miknn_kDistC(SEXP ySEXP, SEXP knnSEXP, SEXP positionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type knn(knnSEXP);
    Rcpp::traits::input_parameter< int >::type position(positionSEXP);
    rcpp_result_gen = Rcpp::wrap(kDistC(y, knn, position));
    return rcpp_result_gen;
END_RCPP
}
// kVector
NumericVector kVector(NumericVector w, int knn);
RcppExport SEXP _miknn_kVector(SEXP wSEXP, SEXP knnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type knn(knnSEXP);
    rcpp_result_gen = Rcpp::wrap(kVector(w, knn));
    return rcpp_result_gen;
END_RCPP
}
// neighbors
NumericVector neighbors(NumericVector y, NumericVector x);
RcppExport SEXP _miknn_neighbors(SEXP ySEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(neighbors(y, x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_miknn_knn_dist", (DL_FUNC) &_miknn_knn_dist, 3},
    {"_miknn_kDistC", (DL_FUNC) &_miknn_kDistC, 3},
    {"_miknn_kVector", (DL_FUNC) &_miknn_kVector, 2},
    {"_miknn_neighbors", (DL_FUNC) &_miknn_neighbors, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_miknn(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
