# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

knn_dist_2 <- function(y, knn) {
    .Call(`_miknn_knn_dist_2`, y, knn)
}

knn_dist <- function(y, k) {
    .Call(`_miknn_knn_dist`, y, k)
}

neighbors <- function(y, x) {
    .Call(`_miknn_neighbors`, y, x)
}

