# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.kVector <- function(w, knn, nthreads = 1L) {
    .Call(`_miknn_kVector`, w, knn, nthreads)
}

kVector <- function(w, knn, nthreads = 1L) {
    .Call(`_miknn_kVector2`, w, knn, nthreads)
}

.neighbors <- function(y, x) {
    .Call(`_miknn_neighbors`, y, x)
}

